/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Entity.Student;
import com.sun.glass.events.KeyEvent;
import java.awt.event.WindowEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author Arman
 */
public class AddDialog extends javax.swing.JDialog {

    /**
     * Creates new form AddDialog
     */
    public AddDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        NameLabel = new javax.swing.JLabel();
        FamilyNameLabel = new javax.swing.JLabel();
        IDLabel = new javax.swing.JLabel();
        GPALabel = new javax.swing.JLabel();
        NameTextField = new javax.swing.JTextField();
        FamilyNameTextField = new javax.swing.JTextField();
        IDTextField = new javax.swing.JTextField();
        GPATextField = new javax.swing.JTextField();
        OKButton = new javax.swing.JButton();
        CancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        NameLabel.setText("Name");

        FamilyNameLabel.setText("Family Name");

        IDLabel.setText("Student ID Number");

        GPALabel.setText("GPA");

        IDTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                IDTextFieldKeyPressed(evt);
            }
        });

        GPATextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GPATextFieldActionPerformed(evt);
            }
        });
        GPATextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                GPATextFieldKeyPressed(evt);
            }
        });

        OKButton.setText("OK");
        OKButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKButtonActionPerformed(evt);
            }
        });

        CancelButton.setText("Cancel");
        CancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(126, 126, 126)
                                .addComponent(GPALabel))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(NameLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(FamilyNameLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(IDLabel, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(FamilyNameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                            .addComponent(IDTextField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(GPATextField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NameTextField)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(OKButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CancelButton)))
                .addContainerGap(111, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(NameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NameLabel))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(FamilyNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FamilyNameLabel))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(IDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IDLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                        .addComponent(GPATextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(GPALabel)))
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CancelButton)
                    .addComponent(OKButton))
                .addGap(38, 38, 38))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GPATextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GPATextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GPATextFieldActionPerformed
    Student St;
    private void OKButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKButtonActionPerformed
        // TODO add your handling code here:
        if (NameTextField.getText().toString().trim().length() != 0 && FamilyNameTextField.getText().toString().trim().length() != 0 && IDTextField.getText().toString().trim().length() != 0 && IDTextField.getText().toString().trim().length() == 9 && GPATextField.getText().toString().trim().length() != 0 && Double.parseDouble(GPATextField.getText()) <= 20) {
            String Name = NameTextField.getText();
            String Family = FamilyNameTextField.getText();
            String ID = IDTextField.getText();
            String GPA = GPATextField.getText();

            St = new Student(Name, Family, ID, GPA);

            this.setVisible(false);
        }
        if (NameTextField.getText().toString().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Please enter Name!");
        } else {
            if (FamilyNameTextField.getText().toString().trim().length() == 0) {
                JOptionPane.showMessageDialog(null, "Please enter Family Name!");
            } else {
                if (IDTextField.getText().toString().trim().length() == 0) {
                    JOptionPane.showMessageDialog(null, "Please enter Student Id Number!");
                } else {
                    if (GPATextField.getText().toString().trim().length() == 0) {
                        JOptionPane.showMessageDialog(null, "Please enter GPA!");
                    } else {
                        if (IDTextField.getText().length() != 9) {
                            JOptionPane.showMessageDialog(null, "Please enter Student ID Number Correctly!");
                        } else {
                            if (Double.parseDouble(GPATextField.getText()) > 20) {
                                JOptionPane.showMessageDialog(null, "Please enter GPA Correctly!");
                            }
                        }
                    }
                }
            }
        }
    }//GEN-LAST:event_OKButtonActionPerformed

    private void IDTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_IDTextFieldKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        int Length = IDTextField.getText().length();
        if (c >= '0' && c <= '9') {
            if (Length < 9) {
                IDTextField.setEditable(true);
            } else {
                IDTextField.setEditable(false);
            }
        } else {
            if (evt.getExtendedKeyCode() == KeyEvent.VK_BACKSPACE || evt.getExtendedKeyCode() == KeyEvent.VK_DELETE) {
                IDTextField.setEditable(true);
            } else {
                IDTextField.setEditable(false);
            }
        }
    }//GEN-LAST:event_IDTextFieldKeyPressed

    int P = 1;
    private void GPATextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_GPATextFieldKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        int Length = GPATextField.getText().length();
        if (Length == 0) {
            P = 1;
        }
        if (c >= '0' && c <= '9') {
            if (Length < 5) {
                GPATextField.setEditable(true);
            } else {
                GPATextField.setEditable(false);
            }
        } else {
            if (evt.getExtendedKeyCode() == KeyEvent.VK_BACKSPACE || evt.getExtendedKeyCode() == KeyEvent.VK_DELETE) {
                GPATextField.setEditable(true);
            } else {
                GPATextField.setEditable(false);
            }
        }
        if (evt.getExtendedKeyCode() == KeyEvent.VK_DECIMAL || evt.getExtendedKeyCode() == KeyEvent.VK_PERIOD) {
            if (P == 1) {
                GPATextField.setEditable(true);
            } else {
                GPATextField.setEditable(false);
            }
            P++;
        }
    }//GEN-LAST:event_GPATextFieldKeyPressed

    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
    }//GEN-LAST:event_CancelButtonActionPerformed

    public void EditAction(String Name, String FamilyName, String IDNum, String GPA) {
        NameTextField.setText(Name);
        FamilyNameTextField.setText(FamilyName);
        IDTextField.setText(IDNum);
        GPATextField.setText(GPA);
    }
    
    public Student GetStudentInfo() {
        return St;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AddDialog dialog = new AddDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelButton;
    private javax.swing.JLabel FamilyNameLabel;
    private javax.swing.JTextField FamilyNameTextField;
    private javax.swing.JLabel GPALabel;
    private javax.swing.JTextField GPATextField;
    private javax.swing.JLabel IDLabel;
    private javax.swing.JTextField IDTextField;
    private javax.swing.JLabel NameLabel;
    private javax.swing.JTextField NameTextField;
    private javax.swing.JButton OKButton;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
